branch-defaults:
  dev:
    environment: mindlogger-atlas-dev
  prod:
    environment: mindlogger-girder-atlas
global:
  application_name: mindlogger_mongo_atlas
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Python 3.6 running
    on 64bit Amazon Linux/2.9.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
